import type { Tables } from "@/lib/supabase/database.types";
import type { AssistantResponse, CampaignOutput } from "@/lib/studio-model";
import type { StudioFeedPost, StudioFeedComment } from "@/lib/studio-recovery";
import bakeryImage from "./media/daybreak-bakery.png";
import bakeryPastries from "./media/daybreak-pastries.png";
import bakeryPeople from "./media/daybreak-baker-story.png";
import bakerySourdough from "./media/daybreak-sourdough.png";
export { bakeryImage };
export const workspaceId = "00000000-0000-4000-8000-000000000001";
export const userId = "00000000-0000-4000-8000-000000000002";
export const campaignId = "00000000-0000-4000-8000-000000000003";
export const conversationId = "00000000-0000-4000-8000-000000000004";
export const now = "2026-09-27T16:00:00.000Z";
const shared = { workspace_id: workspaceId, created_at: now, updated_at: now };
export const workspace = {
  id: workspaceId,
  name: "Daybreak Bakery",
  slug: "synthetic-daybreak",
  created_by: userId,
  created_at: now,
  updated_at: now,
};
export const profile: Tables<"profiles"> = {
  id: userId,
  email: "alex@preview.invalid",
  full_name: "Alex Lane",
  avatar_url: null,
  favorite_pal: "kiana",
  industry: null,
  job_title: "Owner",
  onboarding_completed: true,
  phone: "",
  timezone: "America/Los_Angeles",
  created_at: now,
  updated_at: now,
};
export const settings: Tables<"workspace_settings"> = {
  workspace_id: workspaceId,
  preferred_pal: "kiana",
  default_depth: "strategic",
  email_campaign_ready: true,
  email_palmer_support: false,
  email_usage_alerts: true,
  ai_memory: {},
  last_briefing_at: now,
  updated_at: now,
  week_starts_on: 1,
  active_pal_profile_id: null,
};
export const brand: Tables<"brand_profiles"> = {
  ...shared,
  id: "sample-brand",
  business_name: "Daybreak Bakery",
  creator_type: "Business",
  industry: "Neighborhood bakery",
  description: "A neighborhood bakery making bread from scratch, every morning.",
  primary_audience: "Neighbors who love fresh bread and the people who make it",
  primary_goal: "Build community",
  offers: ["Fresh sourdough", "Morning pastries"],
  voice_traits: ["Warm", "Personal", "Unhurried"],
  avoid_language: ["Best in the world", "Guaranteed results"],
  proof_points: ["Show the early-morning baking process."],
  calls_to_action: ["Come by for your morning loaf"],
  preferred_language: "English",
  platforms: ["facebook", "instagram", "youtube"],
  locations: ["Portland"],
  website: "https://preview.invalid",
  colors: { primary: "#59352b", secondary: "#efc99c", accent: "#7b8752" },
  fonts: { primary: "Georgia", secondary: "Satoshi" },
  social_links: {},
  content_examples: [],
  personal_interests: ["Baking", "Neighborhood stories"],
  personal_story: "The first loaf comes out before the neighborhood wakes up.",
  visual_style: "premium-editorial",
  completion: 82,
  brand_details: {
    mission: "Make something worth waking up for.",
    values: ["Care", "Community", "Craft"],
    primaryColor: "#59352b",
    secondaryColor: "#efc99c",
    accentColor: "#7b8752",
    primaryFont: "Georgia",
    photography: "Warm morning light, flour-dusted hands, real craft.",
    imageStyle: "Candid bakery photography",
    aiRules: "Use approved facts. Ask before adding claims.",
  },
};
export const subscription = {
  workspace_id: workspaceId,
  plan: "creator",
  status: "active",
  billing_interval: "month",
  campaign_allowance: 2,
  current_period_start: "2026-09-01T00:00:00Z",
  current_period_end: "2026-10-01T00:00:00Z",
  cancel_at_period_end: false,
  stripe_customer_id: null,
  stripe_subscription_id: null,
  trial_ends_at: "2026-10-01T00:00:00Z",
  updated_at: now,
};
export const output: CampaignOutput = {
  title: "Made before sunrise",
  primaryLane: "spotlight",
  strategy: {
    bigIdea: "A week of stories about the care behind your morning loaf.",
    audienceInsight: "People connect with the hands and rituals behind something they love.",
    promise: "Meet the craft that happens before the doors open.",
    messagePillars: ["Made from scratch", "The people behind it", "A neighborhood morning"],
    channelPlan: [
      { channel: "Facebook", role: "Tell the morning story" },
      { channel: "Instagram", role: "Show the craft up close" },
      { channel: "YouTube", role: "Meet the baker" },
    ],
  },
  anchor: {
    title: "Before the doors open",
    hook: "Before the town wakes up, our day has already begun.",
    script:
      "[Opening: flour falls across the workbench.]\n\nBAKER: Before the town wakes up, our day has already begun. A little flour. A little patience. A lot of care.\n\n[Close-up: hands shape a fresh loaf.]\n\nBAKER: We make every loaf from scratch. The quiet work happens here, long before you smell the first batch from the street.\n\n[The door opens in the morning light.]\n\nBAKER: Come by for your morning loaf. We’ll have something warm waiting.",
    callToAction: "Come by for your morning loaf.",
    scenes: [
      {
        beat: "Before sunrise",
        visual: "Hands dusting flour across the bench",
        spoken: "Before the town wakes up, our day has already begun.",
        onScreenText: "Made before sunrise",
        broll: ["Shaping dough", "Steam from a fresh loaf"],
      },
    ],
  },
  article: {
    title: "The craft behind every loaf",
    dek: "Some good things happen long before the doors open.",
    sections: [
      {
        heading: "An early start",
        body: "Our mornings begin with flour-dusted hands and a quiet kitchen. Before the neighborhood wakes up, we’re making something worth getting up for.",
      },
      {
        heading: "Made from scratch",
        body: "There’s no shortcut to care. Each loaf is shaped by hand, given its time, and baked for the people who will share it.",
      },
    ],
    keyTakeaways: ["Show the hands behind the work", "Tell a small, personal story"],
    closing: "Come by for your morning loaf.",
  },
  shorts: [
    {
      title: "The first loaf of the day",
      hook: "Your morning starts here. Ours starts a little earlier.",
      script:
        "[0–3s: Flour falls onto the bench.] Your morning starts here.\n[3–12s: Hands knead and shape the dough.] Ours starts a little earlier. Fresh bread, made from scratch.\n[12–20s: A loaf comes out of the oven.] A little patience. A lot of care.\n[20–30s: Morning light across the counter.] Come by for your morning loaf.",
      callToAction: "Save a little room for Daybreak.",
    },
  ],
  captions: [
    {
      platform: "facebook",
      copy: "A good morning starts before sunrise.\n\nA little flour. A little patience. A lot of care. Everything we make starts from scratch, right here at Daybreak.\n\nCome by for your morning loaf.",
    },
  ],
  faq: [
    {
      question: "What makes your morning special?",
      answer: "We make our bread from scratch, with a little patience and a lot of care.",
    },
  ],
  newsletter: {
    subject: "Something worth waking up for",
    body: "Good morning, neighbor.\n\nBefore the town wakes up, our ovens are already warming. This week, we’re taking you behind the counter to meet the hands that shape your morning loaf.\n\nMade from scratch. Every morning.\n\nSee you at Daybreak.",
  },
  carousel: {
    title: "A morning at Daybreak",
    slides: [
      "Before the doors open",
      "Made from scratch",
      "A little patience",
      "Something worth waking up for",
    ],
  },
  platformPosts: [
    {
      id: "sample-facebook",
      platform: "facebook",
      format: "image",
      title: "Made before sunrise",
      hook: "A good morning starts before sunrise.",
      body: "A little flour. A little patience. A lot of care. Everything we make starts from scratch, right here at Daybreak.",
      callToAction: "Come by for your morning loaf.",
      hashtags: [],
      nativeFeature: "Photo post",
      publishNotes: "Pair with the morning baking photograph.",
      slides: [],
      poll: null,
      quiz: null,
    },
  ],
  productionPlan: {
    objective: "Show the care behind the morning loaf.",
    estimatedMinutes: 45,
    location: "Bakery",
    wardrobe: ["Everyday baking apron"],
    props: ["Flour", "Fresh dough", "Bread baskets"],
    deliveryNotes: ["Speak naturally", "Use the quiet morning sounds"],
    shots: [
      { shot: "Hands kneading dough", framing: "Close-up", purpose: "Make the craft tangible" },
    ],
    broll: ["Flour falling", "Fresh bread in morning light"],
    checklist: ["Check sound", "Clear the bench", "Film before opening"],
  },
  schedule: [
    { title: "Made before sunrise", channel: "Facebook", dayOffset: 1 },
    { title: "The first loaf of the day", channel: "Instagram", dayOffset: 3 },
  ],
};
export const campaigns: Tables<"campaigns">[] = [
  {
    ...shared,
    id: campaignId,
    title: output.title,
    created_by: userId,
    conversation_id: conversationId,
    goal: "Bring the neighborhood into the bakery’s morning story",
    topic: output.strategy.bigIdea,
    audience: brand.primary_audience,
    offer: "Fresh bread, made from scratch",
    anchor_format: "campaign_story",
    depth: "strategic",
    primary_lane: "spotlight",
    strategy: output.strategy,
    production_plan: output.productionPlan,
    scheduled_at: null,
    status: "ready",
  },
  {
    ...shared,
    id: "sample-campaign-draft",
    title: "The people behind the counter",
    created_by: userId,
    conversation_id: null,
    goal: "Meet the people who make your morning",
    topic: "A day at Daybreak",
    audience: brand.primary_audience,
    offer: "Morning pastries",
    anchor_format: "authority_video",
    depth: "quick",
    primary_lane: "evergreen",
    strategy: {},
    production_plan: {},
    scheduled_at: null,
    status: "draft",
  },
];
const asset = (
  id: string,
  kind: string,
  title: string,
  content: string,
  metadata: Tables<"campaign_assets">["metadata"],
  order: number,
): Tables<"campaign_assets"> => ({
  ...shared,
  id,
  campaign_id: campaignId,
  kind,
  title,
  content,
  metadata,
  sort_order: order,
  status: "draft",
});
export const assets: Tables<"campaign_assets">[] = [
  asset(
    "sample-facebook",
    "platform_post",
    "Made before sunrise",
    output.captions[0].copy,
    {
      platform: "facebook",
      imageUrl: bakeryPastries,
      imageAlt: "Fresh croissants and morning buns on a tray in the bakery",
      syntheticPreview: true,
    },
    0,
  ),
  asset(
    "sample-caption",
    "caption",
    "The person behind your morning loaf",
    "Before the doors open, there’s someone here making something with care. A little patience, a familiar ritual, and a loaf made to share.\n\nMeet the people behind your morning.\n\n#DaybreakBakery #PeopleBehindTheBread",
    {
      platform: "instagram",
      imageUrl: bakeryPeople,
      imageAlt: "A fictional baker holding a sourdough loaf beside the bakery's bread shelves",
      syntheticPreview: true,
    },
    1,
  ),
  asset(
    "sample-article",
    "article",
    output.article!.title,
    output.article!.sections.map((s) => `## ${s.heading}\n\n${s.body}`).join("\n\n"),
    {},
    2,
  ),
  asset(
    "sample-anchor",
    "anchor_script",
    output.anchor.title,
    output.anchor.script,
    {
      visualType: "storyboard",
      storyboard: [
        { label: "Opening", text: "Flour falls across the workbench." },
        { label: "The craft", text: "Hands shape a fresh loaf." },
        { label: "Invitation", text: "The door opens in the morning light." },
      ],
    },
    3,
  ),
  asset(
    "sample-short",
    "short_script",
    output.shorts[0].title,
    output.shorts[0].script,
    {
      visualType: "storyboard",
      storyboard: [
        { label: "0–3s", text: "Flour falls onto the bench." },
        { label: "3–12s", text: "Hands knead and shape the dough." },
        { label: "12–20s", text: "A loaf comes out of the oven." },
      ],
    },
    4,
  ),
  asset(
    "sample-newsletter",
    "newsletter",
    output.newsletter.subject,
    output.newsletter.body,
    {},
    5,
  ),
  asset(
    "sample-image",
    "image",
    "A loaf, ready to share",
    "A fictional sample photograph of sliced sourdough on a pale tabletop with linen and crumbs.",
    {
      imageUrl: bakerySourdough,
      imageAlt: "Overhead view of sliced sourdough on pale stone with a linen cloth",
      generated: true,
      syntheticPreview: true,
    },
    6,
  ),
];
export const ideas: Tables<"content_ideas">[] = [
  {
    ...shared,
    id: "sample-idea-1",
    body: "The first loaf of the day. Show the little rituals before the doors open.",
    business_problem: "People see the finished bread, but not the care that goes into it.",
    conversation_id: null,
    created_by: userId,
    primary_lane: "spotlight",
    source_type: "text",
    source_url: null,
    source_media_path: null,
    source_metadata: {},
    status: "captured",
  },
  {
    ...shared,
    id: "sample-idea-2",
    body: "Let a baker answer: how do you know when the dough is ready?",
    business_problem: "Give neighbors a useful glimpse of the craft.",
    conversation_id: null,
    created_by: userId,
    primary_lane: "evergreen",
    source_type: "chat",
    source_url: null,
    source_media_path: null,
    source_metadata: {},
    status: "captured",
  },
];
export const calendar: Tables<"calendar_items">[] = [
  {
    ...shared,
    id: "sample-calendar",
    asset_id: "sample-anchor",
    assignee_id: null,
    campaign_id: campaignId,
    channel: "youtube",
    notes: "Review the script before filming.",
    publish_at: "2026-09-29T16:00:00Z",
    status: "planned",
    title: output.anchor.title,
  },
  {
    ...shared,
    id: "sample-calendar-facebook",
    asset_id: "sample-facebook",
    assignee_id: null,
    campaign_id: campaignId,
    channel: "facebook",
    notes: "Copy the caption and pair with the morning photograph.",
    publish_at: "2026-09-30T16:00:00Z",
    status: "planned",
    title: "Made before sunrise",
  },
];
export const conversations: Tables<"conversations">[] = [
  {
    ...shared,
    id: conversationId,
    title: "A week of content for Daybreak",
    pal: "kiana",
    archived: false,
    created_by: userId,
    is_legacy: false,
    last_message_at: now,
    message_count: 2,
  },
  {
    ...shared,
    id: "sample-conversation-2",
    title: "Stories behind the counter",
    pal: "clara",
    archived: false,
    created_by: userId,
    is_legacy: false,
    last_message_at: "2026-09-26T16:00:00Z",
    message_count: 0,
  },
];
export const reply: AssistantResponse = {
  reply:
    "Here’s your campaign: **Made before sunrise.**\n\nA week of stories about the care behind your morning loaf. Your Facebook post, Instagram carousel, article, and video script are ready to review below.",
  headline: "Made before sunrise",
  lane: "spotlight",
  problem: "Show the people and care behind the product.",
  keyPoints: [],
  followUps: ["Make it more personal.", "Give it a warmer voice."],
  recommendations: [],
  memorySuggestions: [],
};
export const messages: Tables<"assistant_messages">[] = [
  {
    id: "sample-message-1",
    workspace_id: workspaceId,
    conversation_id: conversationId,
    pal: "kiana",
    role: "user",
    body: "We filmed a local bakery today. Can we make a week of content?",
    metadata: {},
    user_id: userId,
    created_at: "2026-09-27T15:59:00Z",
  },
  {
    id: "sample-message-2",
    workspace_id: workspaceId,
    conversation_id: conversationId,
    pal: "kiana",
    role: "assistant",
    body: reply.reply,
    metadata: { ...reply, campaignId },
    user_id: null,
    created_at: now,
  },
];
export const feedPosts: StudioFeedPost[] = [
  {
    id: "sample-feed-1",
    workspace_id: workspaceId,
    created_by: userId,
    title: "The best part happens before opening.",
    body: "We have a whole morning story in the Library. What if the next post let people hear the bakery waking up—the flour, the bench, that first oven door? A small detail people can almost smell.",
    lane: "spotlight",
    author: { kind: "pal", name: "Kiana", pal: "kiana" },
    sources: [],
    asset_id: "sample-image",
    generated: true,
    created_at: now,
  },
  {
    id: "sample-feed-2",
    workspace_id: workspaceId,
    created_by: userId,
    title: "One good question can become a week of posts.",
    body: "Your saved idea asks how a baker knows the dough is ready. Start with the answer, then make a short script, a helpful carousel, and a note for the newsletter. Same idea, three different ways in.",
    lane: "evergreen",
    author: { kind: "pal", name: "Clara", pal: "clara" },
    sources: [],
    asset_id: null,
    generated: true,
    created_at: now,
  },
];
export const feedComments: StudioFeedComment[] = [
  {
    id: "sample-feed-reply-1",
    workspace_id: workspaceId,
    post_id: "sample-feed-1",
    created_by: userId,
    body: "Yes. Open on the flour falling. No big intro—just that tiny moment and “Your morning starts here. Ours starts earlier.”",
    author: { kind: "pal", name: "Ryder", pal: "ryder" },
    created_at: now,
  },
  {
    id: "sample-feed-reply-2",
    workspace_id: workspaceId,
    post_id: "sample-feed-1",
    created_by: userId,
    body: "And keep the longer version for the article. The hands are the hook; the person behind them is the story.",
    author: { kind: "pal", name: "Clara", pal: "clara" },
    created_at: now,
  },
];
