import type { Tables } from "@/lib/supabase/database.types";
import type { AssistantResponse, CampaignOutput } from "@/lib/studio-model";

export const workspaceId = "00000000-0000-4000-8000-000000000001";
export const userId = "00000000-0000-4000-8000-000000000002";
export const campaignId = "00000000-0000-4000-8000-000000000003";
export const conversationId = "00000000-0000-4000-8000-000000000004";
export const now = "2026-09-14T16:00:00.000Z";
const shared = { workspace_id: workspaceId, created_at: now, updated_at: now };

export const workspace = {
  id: workspaceId,
  name: "Cedar Workshop",
  slug: "synthetic-cedar",
  created_by: userId,
  created_at: now,
  updated_at: now,
};
export const profile: Tables<"profiles"> = {
  id: userId,
  email: "jamie@preview.invalid",
  full_name: "Jamie Chen",
  avatar_url: null,
  favorite_pal: "kiana",
  industry: null,
  job_title: "Owner",
  onboarding_completed: true,
  phone: "",
  timezone: "America/Los_Angeles",
  created_at: now,
  updated_at: now,
};
export const settings: Tables<"workspace_settings"> = {
  workspace_id: workspaceId,
  preferred_pal: "kiana",
  default_depth: "strategic",
  email_campaign_ready: true,
  email_palmer_support: false,
  email_usage_alerts: true,
  ai_memory: {},
  last_briefing_at: now,
  updated_at: now,
  week_starts_on: 1,
};
export const brand: Tables<"brand_profiles"> = {
  ...shared,
  id: "sample-brand",
  business_name: "Cedar Workshop",
  creator_type: "Business",
  industry: "Custom furniture",
  description: "A sample independent workshop designing and building furniture for everyday homes.",
  primary_audience: "Homeowners choosing a made-to-order dining table",
  primary_goal: "Sell services",
  offers: ["Custom dining tables", "Furniture restoration"],
  voice_traits: ["Clear", "Warm", "Practical"],
  avoid_language: ["Best in the world", "Guaranteed results"],
  proof_points: ["Use real footage of the workshop process."],
  calls_to_action: ["Tell us about your space"],
  preferred_language: "English",
  platforms: ["instagram", "youtube"],
  locations: ["Portland"],
  website: "https://preview.invalid",
  colors: { primary: "#3D1A66" },
  fonts: { primary: "Satoshi" },
  social_links: {},
  content_examples: [],
  personal_interests: ["Woodworking", "Local trails"],
  personal_story: "I like explaining the small choices that make furniture useful.",
  visual_style: "premium-editorial",
  completion: 82,
  brand_details: {
    mission: "Make useful furniture and explain how it is made.",
    values: ["Care", "Clarity"],
    primaryColor: "#3D1A66",
    secondaryColor: "#0A9B8F",
    accentColor: "#5B8A2D",
    primaryFont: "Satoshi",
    aiRules: "Use approved facts. Ask before adding claims.",
  },
};
export const subscription = {
  workspace_id: workspaceId,
  plan: "creator",
  status: "active",
  billing_interval: "month",
  campaign_allowance: 2,
  current_period_start: "2026-09-01T00:00:00Z",
  current_period_end: "2026-10-01T00:00:00Z",
  cancel_at_period_end: false,
  stripe_customer_id: null,
  stripe_subscription_id: null,
  trial_ends_at: "2026-09-21T00:00:00Z",
  updated_at: now,
};

export const output: CampaignOutput = {
  title: "What makes a table fit your home?",
  primaryLane: "spotlight",
  strategy: {
    bigIdea: "Show how the room and everyday habits shape the table.",
    audienceInsight: "Customers need help choosing dimensions before choosing finishes.",
    promise: "A clear starting point for the first workshop conversation.",
    messagePillars: ["Start with the room", "Show the material", "Explain the process"],
    channelPlan: [
      { channel: "YouTube", role: "Explain the decision" },
      { channel: "Instagram", role: "Share useful short examples" },
    ],
  },
  anchor: {
    title: "Start with your space",
    hook: "Before choosing a finish, measure the room you actually use.",
    script:
      "A dining table has to work on an ordinary Tuesday. Start with the people who sit around it and the space you need to move.\n\nWe look at the room, the seating, and the way your household uses the table before discussing the finish. Bring a few measurements and we can talk through the choices.",
    callToAction: "Tell us about your space.",
    scenes: [
      {
        beat: "Room",
        visual: "Measure the clear space around a table.",
        spoken: "Start with the room you use every day.",
        onScreenText: "Measure the room first",
        broll: ["Tape measure beside a chair", "Wood samples on the bench"],
      },
    ],
  },
  article: {
    title: "Three measurements to bring to the workshop",
    dek: "A practical starting point for a custom table.",
    sections: [
      {
        heading: "Start with the room",
        body: "Measure the usable floor space and note doorways and other furniture.",
      },
      {
        heading: "Think about seating",
        body: "Describe a usual meal and the largest group you expect to host.",
      },
    ],
    keyTakeaways: ["Measure your room", "Describe daily use"],
    closing: "Bring your measurements to the first conversation.",
  },
  shorts: [
    {
      title: "Leave room for the chair",
      hook: "The table is only part of the footprint.",
      script: "Pull a chair out and measure the room people need to pass behind it.",
      callToAction: "Save this before measuring.",
    },
  ],
  captions: [
    {
      platform: "instagram",
      copy: "Your table starts with your room. Bring the dimensions and the way you use it; we will walk through the next choices.",
    },
  ],
  faq: [
    {
      question: "What should I bring to the first conversation?",
      answer: "Your room measurements and a few notes about how you want to use the table.",
    },
  ],
  newsletter: {
    subject: "Start with the room",
    body: "This month we are explaining the small decisions behind a useful dining table. Start with your space, your seating, and the way you use both.",
  },
  carousel: {
    title: "Before you choose a table",
    slides: [
      "Measure the room",
      "Make space for chairs",
      "Describe daily use",
      "Bring your questions",
    ],
  },
  platformPosts: [
    {
      id: "sample-post",
      platform: "instagram",
      format: "carousel",
      title: "Measure before choosing",
      hook: "A useful table starts with the room.",
      body: "Three details to bring to your workshop conversation.",
      callToAction: "Save these steps.",
      hashtags: [],
      nativeFeature: "Carousel",
      publishNotes: "Review dimensions and examples before publishing.",
      slides: ["Measure the room", "Make space for chairs", "Describe daily use"],
      poll: null,
      quiz: null,
    },
  ],
  productionPlan: {
    objective: "Explain how room measurements guide a table design.",
    estimatedMinutes: 45,
    location: "Workshop",
    wardrobe: ["Everyday workshop clothing"],
    props: ["Tape measure", "Wood samples"],
    deliveryNotes: ["Speak naturally", "Show each measurement as you explain it"],
    shots: [
      {
        shot: "Opening explanation",
        framing: "Medium",
        purpose: "Introduce the practical question",
      },
    ],
    broll: ["Measuring a tabletop", "Comparing material samples"],
    checklist: ["Check sound", "Clear the bench", "Confirm sample measurements"],
  },
  schedule: [
    { title: "Start with your space", channel: "YouTube", dayOffset: 1 },
    { title: "Leave room for the chair", channel: "Instagram", dayOffset: 3 },
  ],
};
export const campaigns: Tables<"campaigns">[] = [
  {
    ...shared,
    id: campaignId,
    title: output.title,
    created_by: userId,
    conversation_id: conversationId,
    goal: "Help customers prepare for their first furniture consultation",
    topic: output.strategy.bigIdea,
    audience: brand.primary_audience,
    offer: "Custom dining tables",
    anchor_format: "service_explainer",
    depth: "strategic",
    primary_lane: "spotlight",
    strategy: output.strategy,
    production_plan: output.productionPlan,
    scheduled_at: null,
    status: "ready",
  },
  {
    ...shared,
    id: "sample-campaign-draft",
    title: "A closer look at the workshop",
    created_by: userId,
    conversation_id: null,
    goal: "Introduce the people and process",
    topic: "One day at the workbench",
    audience: brand.primary_audience,
    offer: "Custom furniture",
    anchor_format: "authority_video",
    depth: "quick",
    primary_lane: "evergreen",
    strategy: {},
    production_plan: {},
    scheduled_at: null,
    status: "draft",
  },
];
export const assets: Tables<"campaign_assets">[] = [
  {
    ...shared,
    id: "sample-anchor",
    campaign_id: campaignId,
    kind: "anchor_script",
    title: output.anchor.title,
    content: output.anchor.script,
    metadata: {},
    sort_order: 0,
    status: "approved",
  },
  {
    ...shared,
    id: "sample-short",
    campaign_id: campaignId,
    kind: "short_script",
    title: output.shorts[0].title,
    content: output.shorts[0].script,
    metadata: {},
    sort_order: 1,
    status: "draft",
  },
  {
    ...shared,
    id: "sample-caption",
    campaign_id: campaignId,
    kind: "caption",
    title: "Your table starts with your room",
    content: output.captions[0].copy,
    metadata: { platform: "instagram" },
    sort_order: 2,
    status: "draft",
  },
  {
    ...shared,
    id: "sample-newsletter",
    campaign_id: campaignId,
    kind: "newsletter",
    title: output.newsletter.subject,
    content: output.newsletter.body,
    metadata: {},
    sort_order: 3,
    status: "approved",
  },
];
export const ideas: Tables<"content_ideas">[] = [
  {
    ...shared,
    id: "sample-idea-1",
    body: "Show how different wood finishes look in daylight.",
    business_problem: "Customers find it difficult to compare finishes online.",
    conversation_id: null,
    created_by: userId,
    primary_lane: "spotlight",
    source_type: "text",
    source_url: null,
    source_media_path: null,
    source_metadata: {},
    status: "captured",
  },
  {
    ...shared,
    id: "sample-idea-2",
    body: "Explain what happens during a furniture restoration assessment.",
    business_problem: "People do not know what to bring to an assessment.",
    conversation_id: null,
    created_by: userId,
    primary_lane: "evergreen",
    source_type: "chat",
    source_url: null,
    source_media_path: null,
    source_metadata: {},
    status: "captured",
  },
];
export const calendar: Tables<"calendar_items">[] = [
  {
    ...shared,
    id: "sample-calendar",
    asset_id: "sample-anchor",
    assignee_id: null,
    campaign_id: campaignId,
    channel: "youtube",
    notes: "Final review before publication.",
    publish_at: "2026-09-17T16:00:00Z",
    status: "planned",
    title: output.anchor.title,
  },
];
export const conversations: Tables<"conversations">[] = [
  {
    ...shared,
    id: conversationId,
    title: "Help customers measure their space",
    pal: "kiana",
    archived: false,
    created_by: userId,
    is_legacy: false,
    last_message_at: now,
    message_count: 2,
  },
  {
    ...shared,
    id: "sample-conversation-2",
    title: "Workshop questions worth answering",
    pal: "clara",
    archived: false,
    created_by: userId,
    is_legacy: false,
    last_message_at: "2026-09-13T16:00:00Z",
    message_count: 0,
  },
];
export const reply: AssistantResponse = {
  reply:
    "Start with the question customers ask before choosing a finish: **will this table fit the way we live?**\n\nShow one room measurement, the space behind a chair, and the materials on your bench. That gives people something useful to bring to the first conversation.",
  headline: "Help customers start with their own space",
  lane: "spotlight",
  problem: "Customers need a practical starting point.",
  keyPoints: [
    "Show the room measurement",
    "Leave space for a chair",
    "Bring real material samples",
  ],
  followUps: ["Can we turn that into a short script?"],
  recommendations: [
    {
      title: "Create a measuring guide",
      reason: "It answers a specific question before a consultation.",
      nextStep: "Film a short walkthrough of the measurements to bring.",
      videoKey: null,
    },
  ],
  memorySuggestions: [],
};
export const messages: Tables<"assistant_messages">[] = [
  {
    id: "sample-message-1",
    workspace_id: workspaceId,
    conversation_id: conversationId,
    pal: "kiana",
    role: "user",
    body: "People ask where to start when choosing a custom table. What should we explain?",
    metadata: {},
    user_id: userId,
    created_at: "2026-09-14T15:59:00Z",
  },
  {
    id: "sample-message-2",
    workspace_id: workspaceId,
    conversation_id: conversationId,
    pal: "kiana",
    role: "assistant",
    body: reply.reply,
    metadata: reply,
    user_id: null,
    created_at: now,
  },
];
