/**
 * Curated starter options for every "blank box" in the Studio.
 * Every list is a starting point — each guided field also accepts custom text.
 */

export const brandSuggestions = {
  personal_interests: [
    "Fishing",
    "Hiking and trails",
    "Coaching youth sports",
    "Cooking and grilling",
    "Restoring cars",
    "Woodworking",
    "Live music",
    "Golf",
    "Reading",
    "Travel",
    "Running",
    "Volunteering",
    "Gardening",
    "Photography",
    "Board games with the kids",
  ],
  personal_story: [
    "I started this after watching a family member get talked into something they did not understand.",
    "I spent years on the other side of this industry before deciding to do it differently.",
    "Most weekends I am outdoors with my family, and that pace shapes how we work.",
    "I am the person friends call when they need this explained in plain language.",
  ],
  industry: [
    "Professional services",
    "Construction & trades",
    "Real estate",
    "Health & wellness",
    "Fitness & performance",
    "Technology / SaaS",
    "Creative agency",
    "Education & training",
    "Retail & ecommerce",
    "Hospitality & food",
    "Financial services",
    "Nonprofit",
    "Manufacturing",
    "Entertainment & media",
  ],
  description: [
    "We do the work most people in our category outsource, and we show how it happens.",
    "We help a specific kind of customer solve one expensive problem, start to finish.",
    "We make a product people already want easier to understand and easier to buy.",
    "We teach what we know so the right clients arrive already convinced.",
  ],
  offers: [
    "Done-for-you service package",
    "Monthly retainer or membership",
    "One-off project or build",
    "Consultation or discovery call",
    "Digital product or download",
    "Workshop, course, or training",
    "Physical product line",
    "Speaking or appearances",
  ],
  primary_audience: [
    "Small business owners in my region",
    "Operations or facilities managers",
    "Founders scaling past their first hires",
    "Homeowners planning a major project",
    "Marketing leads at mid-size companies",
    "Individuals researching before they buy",
    "Internal teams who need one clear process",
  ],
  customers: [
    "Repeat clients who came back for a second project",
    "Referral-driven customers who arrive pre-sold",
    "First-time buyers who need reassurance",
    "Long-term contract accounts",
    "A community that follows the work more than the offer",
  ],
  competitors: [
    "Doing nothing and living with the problem",
    "Handling it in-house",
    "The cheapest option in the market",
    "A large national brand",
    "A freelancer or solo operator",
    "A DIY tool or template",
  ],
  proof_points: [
    "Years in business",
    "Number of projects or clients completed",
    "A named certification or license",
    "A measurable client outcome we can document",
    "A written testimonial we have permission to use",
    "An award, feature, or press mention",
  ],
  calls_to_action: [
    "Book a free consultation",
    "Request a quote",
    "Send us a message",
    "Download the guide",
    "Join the waitlist",
    "Subscribe for the next one",
    "Visit the website",
  ],
  mission: [
    "Make a confusing purchase feel obvious and safe.",
    "Do excellent work and let the work do the selling.",
    "Give people the information they need before they need us.",
    "Raise the standard in a category people expect little from.",
  ],
  values: [
    "Clarity over cleverness",
    "Show the work, not the pitch",
    "Do it right the first time",
    "Respect people's time",
    "Honest pricing, no surprises",
    "Long relationships over quick sales",
  ],
  taglines: [
    "Say what you do, then prove it.",
    "Built right. Explained clearly.",
    "The work speaks. We just film it.",
  ],
  voice_traits: [
    "Direct",
    "Warm",
    "Confident",
    "Plainspoken",
    "Expert",
    "Practical",
    "Calm",
    "Witty",
    "Encouraging",
    "No-nonsense",
    "Optimistic",
    "Understated",
  ],
  avoid_language: [
    "Hype and superlatives",
    "Corporate jargon",
    "Guarantees we cannot back up",
    "Fear-based selling",
    "Slang or memes",
    "Emojis",
    "Competitor callouts",
  ],
  platforms: [
    "YouTube",
    "Instagram",
    "TikTok",
    "LinkedIn",
    "Facebook",
    "Threads",
    "Website",
    "Email newsletter",
  ],
  typography: [
    "One bold sans-serif for headlines, one clean sans for body. Nothing decorative.",
    "A serif headline for authority paired with a neutral sans body.",
    "All-caps condensed headlines with generous letter spacing.",
    "Large type, few words, lots of breathing room.",
  ],
  photography: [
    "Real work in progress — no stock, no staging.",
    "Natural light, real people, minimal retouching.",
    "Clean studio shots on a plain background.",
    "Documentary style: candid, on location, shot as it happens.",
    "Product-forward with simple, uncluttered backgrounds.",
  ],
  imageStyle: [
    "Simple flat graphics with one accent color.",
    "Photo-led with minimal text overlays.",
    "Diagram-first — explain the process visually.",
    "Bold type on solid color blocks.",
    "Soft dimensional illustration.",
  ],
  motion: [
    "Cuts, not transitions. Keep it quick and clean.",
    "Gentle fades and slow pushes only.",
    "Text appears one line at a time, never all at once.",
    "No spinning, bouncing, or sliding text.",
  ],
  editing: [
    "Trim every pause. Start on the first useful word.",
    "Captions burned in on every short-form video.",
    "One idea per cut — no stacked ideas.",
    "End on the call to action, always.",
  ],
  videoExamples: [
    "A competitor video we admire",
    "A YouTube channel with the right tone",
    "A brand film we want to feel like",
  ],
  contentExamples: [
    "Our best-performing post so far",
    "A blog article we're proud of",
    "A customer story we've already told",
  ],
  aiRules: [
    "Never invent statistics, results, or testimonials.",
    "Always write at a plain reading level.",
    "Use our exact service names, never generic substitutes.",
    "Never promise timelines or pricing.",
  ],
} as const;

export type BrandSuggestionKey = keyof typeof brandSuggestions;
