const Colors = {
  light: {
    text: "#1F2328",
    textSecondary: "#656D76",
    textTertiary: "#8B949E",
    background: "#FFFFFF",
    backgroundSecondary: "#F6F8FA",
    backgroundTertiary: "#EAEEF2",
    card: "#FFFFFF",
    cardElevated: "#FFFFFF",
    tint: "#6B3FA0",
    tabIconDefault: "#8B949E",
    tabIconSelected: "#6B3FA0",
    primary: "#6B3FA0",
    primaryLight: "#F3EEFB",
    primaryMuted: "#A78BCA",
    accent: "#D97706",
    border: "rgba(31,35,40,0.15)",
    borderStrong: "rgba(31,35,40,0.15)",
    borderSubtle: "rgba(31,35,40,0.08)",
    separator: "rgba(31,35,40,0.08)",
    divider: "#D0D7DE",
    success: "#1A7F37",
    error: "#CF222E",
    overlay: "rgba(0,0,0,0.4)",
  },
  pal: {
    reel: "#E8720C",
    reelLight: "#FFF4EB",
    system: "#0A9B8F",
    systemLight: "#EDFAF8",
    evergreen: "#5B8A2D",
    evergreenLight: "#F0F7E8",
    spotlight: "#6B3FA0",
    spotlightLight: "#F3EEFB",
  },
  shadow: {
    sm: {
      shadowColor: "#1F2328",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 3,
      elevation: 1,
    },
    md: {
      shadowColor: "#1F2328",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    lg: {
      shadowColor: "#1F2328",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 5,
    },
  },
};

export default Colors;
