const Colors = {
  light: {
    text: "#000000",
    textSecondary: "#8E8E93",
    textTertiary: "#AEAEB2",
    background: "#FFFFFF",
    backgroundSecondary: "#F2F2F7",
    backgroundTertiary: "#E5E5EA",
    card: "#FFFFFF",
    cardElevated: "#FFFFFF",
    tint: "#6B3FA0",
    tabIconDefault: "#8E8E93",
    tabIconSelected: "#6B3FA0",
    primary: "#6B3FA0",
    primaryLight: "#F3EEFB",
    primaryMuted: "#A78BCA",
    accent: "#D97706",
    border: "rgba(0,0,0,0.06)",
    borderStrong: "rgba(0,0,0,0.1)",
    separator: "rgba(0,0,0,0.04)",
    success: "#34C759",
    error: "#FF3B30",
    overlay: "rgba(0,0,0,0.4)",
  },
  pal: {
    reel: "#E8720C",
    reelLight: "#FFF4EB",
    system: "#0A9B8F",
    systemLight: "#EDFAF8",
    evergreen: "#5B8A2D",
    evergreenLight: "#F0F7E8",
    spotlight: "#6B3FA0",
    spotlightLight: "#F3EEFB",
  },
  shadow: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 3,
      elevation: 1,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 5,
    },
  },
};

export default Colors;
