import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Camera, Check, MessageCircle, RefreshCw, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PageShell } from "@/components/site/PageShell";
import {
  MISSION_GOALS,
  PAL_FEED,
  PAL_LANES,
  recommendLane,
  type MissionGoal,
} from "@/lib/dream-suite";

type Tool = "mission" | "camera" | "ask";
const QUIZ = [
  "I can explain my offer in one clean sentence.",
  "I know exactly who one video is meant to help.",
  "I can name a real example instead of speaking in generalities.",
  "I have a quiet place with light in front of me.",
  "I can speak to one person instead of performing for everyone.",
];

function GamesPage() {
  const [tool, setTool] = useState<Tool>("mission");
  const [goal, setGoal] = useState<MissionGoal>("trust");
  const [answers, setAnswers] = useState<boolean[]>(() => QUIZ.map(() => false));
  const [question, setQuestion] = useState("");
  const [asked, setAsked] = useState("");
  const [feed, setFeed] = useState([...PAL_FEED].slice(0, 4));
  const result = MISSION_GOALS[goal];
  const score = answers.filter(Boolean).length;

  useEffect(() => {
    const key = "ph.pals-feed.visit";
    const visit = Number(window.sessionStorage.getItem(key) ?? "0") + 1;
    window.sessionStorage.setItem(key, String(visit));
    const offset = visit % PAL_FEED.length;
    setFeed(Array.from({ length: 4 }, (_, index) => PAL_FEED[(offset + index) % PAL_FEED.length]));
  }, []);

  const recommendation = useMemo(() => (asked ? recommendLane(asked) : null), [asked]);

  return (
    <PageShell>
      <section className="px-4 pb-12 pt-14">
        <div className="mx-auto max-w-6xl">
          <h1 className="max-w-[10ch] text-5xl font-extrabold leading-[0.94] tracking-[-0.06em] sm:text-7xl lg:text-8xl">
            Play with a real problem.
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-muted-foreground">
            Not arcade games. Small tools that help you leave with a better hook, a clearer shoot,
            or the right Pal.
          </p>
          <div className="mt-10 flex gap-2 overflow-x-auto pb-2" role="tablist">
            {(
              [
                { id: "mission", label: "Mission Spinner", icon: Sparkles },
                { id: "camera", label: "Camera-Ready Check", icon: Camera },
                { id: "ask", label: "Ask the Pals", icon: MessageCircle },
              ] as const
            ).map((item) => (
              <button
                key={item.id}
                type="button"
                role="tab"
                aria-selected={tool === item.id}
                onClick={() => setTool(item.id)}
                className={`inline-flex min-h-12 shrink-0 items-center gap-2 rounded-full px-5 font-semibold ${tool === item.id ? "bg-ink text-white" : "border border-border"}`}
              >
                <item.icon className="size-4" />
                {item.label}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="px-4 pb-20">
        <div className="mx-auto max-w-6xl rounded-[2.5rem] border border-border bg-secondary p-5 sm:p-10">
          {tool === "mission" && (
            <div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]">
              <div>
                <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
                  Pick a goal
                </p>
                <div className="mt-4 grid gap-2">
                  {(Object.keys(MISSION_GOALS) as MissionGoal[]).map((key) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => setGoal(key)}
                      className={`min-h-14 rounded-2xl px-5 text-left font-semibold ${goal === key ? "bg-white shadow-soft" : "hover:bg-white/60"}`}
                    >
                      {MISSION_GOALS[key].label}
                    </button>
                  ))}
                </div>
              </div>
              <div className="rounded-[2rem] bg-white p-6 sm:p-8">
                <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-reel">
                  Mission generated by {result.lane}
                </p>
                <h2 className="mt-5 text-3xl font-extrabold">“{result.hook}”</h2>
                <div className="mt-7 grid gap-6 sm:grid-cols-2">
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">
                      Shot list
                    </p>
                    <ol className="mt-3 space-y-2">
                      {result.shots.map((shot, index) => (
                        <li key={shot} className="flex gap-3 text-sm">
                          <span className="font-mono text-muted-foreground">0{index + 1}</span>
                          {shot}
                        </li>
                      ))}
                    </ol>
                  </div>
                  <div>
                    <p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">
                      Finish with
                    </p>
                    <p className="mt-3 text-lg font-semibold">{result.cta}</p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => {
                    const keys = Object.keys(MISSION_GOALS) as MissionGoal[];
                    setGoal(keys[(keys.indexOf(goal) + 1) % keys.length]);
                  }}
                  className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-full border border-border px-5 text-sm font-semibold"
                >
                  <RefreshCw className="size-4" /> Spin again
                </button>
              </div>
            </div>
          )}

          {tool === "camera" && (
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-extrabold sm:text-5xl">
                Are you ready to press record?
              </h2>
              <p className="mt-4 text-muted-foreground">
                Check what is true today. This is preparation, not a personality test.
              </p>
              <div className="mt-8 divide-y divide-border border-y border-border">
                {QUIZ.map((item, index) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() =>
                      setAnswers((current) =>
                        current.map((value, itemIndex) => (itemIndex === index ? !value : value)),
                      )
                    }
                    className="flex min-h-16 w-full items-center gap-4 py-3 text-left"
                  >
                    <span
                      className={`grid size-7 shrink-0 place-items-center rounded-full border ${answers[index] ? "border-evergreen bg-evergreen text-white" : "border-border bg-white"}`}
                    >
                      {answers[index] && <Check className="size-4" />}
                    </span>
                    <span className="font-medium">{item}</span>
                  </button>
                ))}
              </div>
              <div className="mt-8 rounded-[2rem] bg-white p-6">
                <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
                  Your readiness · {score}/5
                </p>
                <h3 className="mt-3 text-2xl font-bold">
                  {score >= 4
                    ? "You are ready. Stop rehearsing and make the first useful take."
                    : score >= 2
                      ? "You are close. Fix the missing conditions before asking for confidence."
                      : "Start with clarity, not a camera. The Pals can help you shape the message first."}
                </h3>
                <Link
                  to={score >= 4 ? "/production-guide" : "/find-your-pal"}
                  className="mt-5 inline-flex min-h-11 items-center gap-2 font-semibold underline underline-offset-4"
                >
                  Take the next step <ArrowRight className="size-4" />
                </Link>
              </div>
            </div>
          )}

          {tool === "ask" && (
            <div className="grid gap-8 lg:grid-cols-[1fr_0.85fr]">
              <div>
                <h2 className="text-3xl font-extrabold sm:text-5xl">
                  Ask the team, not a blank chatbot.
                </h2>
                <p className="mt-4 text-muted-foreground">
                  This guided matcher listens for the business problem and points you to the right
                  expert lane. It does not pretend to be a human or generative AI.
                </p>
                <label className="mt-8 block">
                  <span className="sr-only">Your question</span>
                  <textarea
                    value={question}
                    onChange={(event) => setQuestion(event.target.value)}
                    rows={6}
                    className="w-full rounded-[2rem] border border-border bg-white p-5"
                    placeholder="What keeps happening in your business?"
                  />
                </label>
                <button
                  type="button"
                  onClick={() => setAsked(question.trim())}
                  className="mt-3 inline-flex min-h-12 items-center gap-2 rounded-full bg-ink px-6 font-semibold text-white"
                >
                  Ask the Pals <ArrowRight className="size-4" />
                </button>
              </div>
              <div className="rounded-[2rem] bg-white p-6">
                {recommendation ? (
                  <>
                    <div className="flex items-end justify-center">
                      {recommendation.people.map((person) => (
                        <img
                          key={person.name}
                          src={person.image}
                          alt={person.name}
                          className="h-44 w-auto object-contain"
                        />
                      ))}
                    </div>
                    <p
                      className="mt-4 font-mono text-[10px] uppercase tracking-[0.18em]"
                      style={{ color: recommendation.color }}
                    >
                      {recommendation.label} is listening
                    </p>
                    <h3 className="mt-3 text-2xl font-bold">{recommendation.promise}</h3>
                    <p className="mt-3 text-sm text-muted-foreground">
                      Start here because: {recommendation.problem}
                    </p>
                    <Link
                      to={recommendation.path}
                      className="mt-6 inline-flex min-h-11 items-center gap-2 font-semibold underline underline-offset-4"
                    >
                      Open this lane <ArrowRight className="size-4" />
                    </Link>
                  </>
                ) : (
                  <div className="grid min-h-80 place-items-center text-center text-muted-foreground">
                    <div>
                      <MessageCircle className="mx-auto size-9" />
                      <p className="mt-4">Your Pal match will appear here.</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </section>

      <section className="bg-ink px-4 py-16 text-white">
        <div className="mx-auto max-w-6xl">
          <div className="flex flex-wrap items-end justify-between gap-5">
            <div>
              <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/50">
                Fresh from the Pals
              </p>
              <h2 className="mt-2 text-3xl font-extrabold sm:text-5xl">
                A different field note each visit.
              </h2>
            </div>
            <button
              type="button"
              onClick={() =>
                setFeed((current) => [
                  ...current.slice(1),
                  PAL_FEED[Math.floor(Math.random() * PAL_FEED.length)],
                ])
              }
              className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/25 px-5 text-sm font-semibold"
            >
              <RefreshCw className="size-4" /> Refresh feed
            </button>
          </div>
          <div className="mt-8 grid gap-px overflow-hidden rounded-[2rem] bg-white/15 sm:grid-cols-2">
            {feed.map((item, index) => {
              const lane = PAL_LANES.find((candidate) => candidate.key === item.lane)!;
              return (
                <article key={`${item.pal}-${index}`} className="min-h-52 bg-ink p-6">
                  <span
                    className="font-mono text-[10px] uppercase tracking-[0.18em]"
                    style={{ color: lane.color }}
                  >
                    {item.pal} · {lane.label}
                  </span>
                  <p className="mt-7 text-xl font-semibold leading-snug">“{item.text}”</p>
                </article>
              );
            })}
          </div>
        </div>
      </section>
    </PageShell>
  );
}

export const Route = createFileRoute("/games")({
  head: () => ({
    meta: [
      { title: "Games & Guided Tools | Palmer House Productions" },
      {
        name: "description",
        content:
          "Use the Palmer House mission spinner, camera-ready check, Pal matcher, and fresh field-note feed.",
      },
    ],
  }),
  component: GamesPage,
});
