/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalsRouteImport } from './routes/pals'
import { Route as IndexRouteImport } from './routes/index'

const PalsRoute = PalsRouteImport.update({
  id: '/pals',
  path: '/pals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pals': typeof PalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pals': typeof PalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pals': typeof PalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pals'
  id: '__root__' | '/' | '/pals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalsRoute: typeof PalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pals': {
      id: '/pals'
      path: '/pals'
      fullPath: '/pals'
      preLoaderRoute: typeof PalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalsRoute: PalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
