/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WebinarRouteImport } from './routes/webinar'
import { Route as VideoSystemAssessmentRouteImport } from './routes/video-system-assessment'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemPalRouteImport } from './routes/system-pal'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as SpotlightPalRouteImport } from './routes/spotlight-pal'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReelPalRouteImport } from './routes/reel-pal'
import { Route as ProductionPricingRouteImport } from './routes/production-pricing'
import { Route as ProductionGuideRouteImport } from './routes/production-guide'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PalsRouteImport } from './routes/pals'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FindYourPalRouteImport } from './routes/find-your-pal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EvergreenPalRouteImport } from './routes/evergreen-pal'
import { Route as ContentStrategyRouteImport } from './routes/content-strategy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AiPovRouteImport } from './routes/ai-pov'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as StudioSuccessRouteImport } from './routes/studio.success'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioRoadmapRouteImport } from './routes/studio.roadmap'
import { Route as StudioOnboardingRouteImport } from './routes/studio.onboarding'
import { Route as StudioLibraryRouteImport } from './routes/studio.library'
import { Route as StudioIdeasRouteImport } from './routes/studio.ideas'
import { Route as StudioDashboardRouteImport } from './routes/studio.dashboard'
import { Route as StudioCalendarRouteImport } from './routes/studio.calendar'
import { Route as StudioBrandRouteImport } from './routes/studio.brand'
import { Route as StudioBillingRouteImport } from './routes/studio.billing'
import { Route as StudioAssistantRouteImport } from './routes/studio.assistant'
import { Route as StudioApprovalsRouteImport } from './routes/studio.approvals'
import { Route as ServicesVideoProductionRouteImport } from './routes/services.video-production'
import { Route as ServicesPostProductionRouteImport } from './routes/services.post-production'
import { Route as ServicesDiyDownloadsRouteImport } from './routes/services.diy-downloads'
import { Route as ResourcesReviewsRouteImport } from './routes/resources.reviews'
import { Route as MembershipSprintRouteImport } from './routes/membership.sprint'
import { Route as MembershipPricingRouteImport } from './routes/membership.pricing'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as StudioCampaignsIndexRouteImport } from './routes/studio.campaigns.index'
import { Route as StudioCampaignsCampaignIdRouteImport } from './routes/studio.campaigns.$campaignId'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarRoute = WebinarRouteImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSystemAssessmentRoute = VideoSystemAssessmentRouteImport.update({
  id: '/video-system-assessment',
  path: '/video-system-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemPalRoute = SystemPalRouteImport.update({
  id: '/system-pal',
  path: '/system-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightPalRoute = SpotlightPalRouteImport.update({
  id: '/spotlight-pal',
  path: '/spotlight-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelPalRoute = ReelPalRouteImport.update({
  id: '/reel-pal',
  path: '/reel-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionPricingRoute = ProductionPricingRouteImport.update({
  id: '/production-pricing',
  path: '/production-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionGuideRoute = ProductionGuideRouteImport.update({
  id: '/production-guide',
  path: '/production-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PalsRoute = PalsRouteImport.update({
  id: '/pals',
  path: '/pals',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FindYourPalRoute = FindYourPalRouteImport.update({
  id: '/find-your-pal',
  path: '/find-your-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EvergreenPalRoute = EvergreenPalRouteImport.update({
  id: '/evergreen-pal',
  path: '/evergreen-pal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStrategyRoute = ContentStrategyRouteImport.update({
  id: '/content-strategy',
  path: '/content-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPovRoute = AiPovRouteImport.update({
  id: '/ai-pov',
  path: '/ai-pov',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSuccessRoute = StudioSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioRoadmapRoute = StudioRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOnboardingRoute = StudioOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdeasRoute = StudioIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDashboardRoute = StudioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCalendarRoute = StudioCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBrandRoute = StudioBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBillingRoute = StudioBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAssistantRoute = StudioAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => StudioRoute,
} as any)
const StudioApprovalsRoute = StudioApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => StudioRoute,
} as any)
const ServicesVideoProductionRoute = ServicesVideoProductionRouteImport.update({
  id: '/services/video-production',
  path: '/services/video-production',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPostProductionRoute = ServicesPostProductionRouteImport.update({
  id: '/services/post-production',
  path: '/services/post-production',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDiyDownloadsRoute = ServicesDiyDownloadsRouteImport.update({
  id: '/services/diy-downloads',
  path: '/services/diy-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesReviewsRoute = ResourcesReviewsRouteImport.update({
  id: '/resources/reviews',
  path: '/resources/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipSprintRoute = MembershipSprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => MembershipRoute,
} as any)
const MembershipPricingRoute = MembershipPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MembershipRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCampaignsIndexRoute = StudioCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCampaignsCampaignIdRoute =
  StudioCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => StudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-pov': typeof AiPovRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/contact': typeof ContactRoute
  '/content-strategy': typeof ContentStrategyRoute
  '/evergreen-pal': typeof EvergreenPalRoute
  '/faq': typeof FaqRoute
  '/find-your-pal': typeof FindYourPalRoute
  '/games': typeof GamesRoute
  '/integrations': typeof IntegrationsRoute
  '/membership': typeof MembershipRouteWithChildren
  '/pals': typeof PalsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/production-guide': typeof ProductionGuideRoute
  '/production-pricing': typeof ProductionPricingRoute
  '/reel-pal': typeof ReelPalRoute
  '/shop': typeof ShopRoute
  '/spotlight-pal': typeof SpotlightPalRoute
  '/startups': typeof StartupsRoute
  '/studio': typeof StudioRouteWithChildren
  '/system-pal': typeof SystemPalRoute
  '/terms': typeof TermsRoute
  '/video-system-assessment': typeof VideoSystemAssessmentRoute
  '/webinar': typeof WebinarRoute
  '/work': typeof WorkRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/membership/pricing': typeof MembershipPricingRoute
  '/membership/sprint': typeof MembershipSprintRoute
  '/resources/reviews': typeof ResourcesReviewsRoute
  '/services/diy-downloads': typeof ServicesDiyDownloadsRoute
  '/services/post-production': typeof ServicesPostProductionRoute
  '/services/video-production': typeof ServicesVideoProductionRoute
  '/studio/approvals': typeof StudioApprovalsRoute
  '/studio/assistant': typeof StudioAssistantRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/ideas': typeof StudioIdeasRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/success': typeof StudioSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-pov': typeof AiPovRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/contact': typeof ContactRoute
  '/content-strategy': typeof ContentStrategyRoute
  '/evergreen-pal': typeof EvergreenPalRoute
  '/faq': typeof FaqRoute
  '/find-your-pal': typeof FindYourPalRoute
  '/games': typeof GamesRoute
  '/integrations': typeof IntegrationsRoute
  '/membership': typeof MembershipRouteWithChildren
  '/pals': typeof PalsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/production-guide': typeof ProductionGuideRoute
  '/production-pricing': typeof ProductionPricingRoute
  '/reel-pal': typeof ReelPalRoute
  '/shop': typeof ShopRoute
  '/spotlight-pal': typeof SpotlightPalRoute
  '/startups': typeof StartupsRoute
  '/system-pal': typeof SystemPalRoute
  '/terms': typeof TermsRoute
  '/video-system-assessment': typeof VideoSystemAssessmentRoute
  '/webinar': typeof WebinarRoute
  '/work': typeof WorkRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/membership/pricing': typeof MembershipPricingRoute
  '/membership/sprint': typeof MembershipSprintRoute
  '/resources/reviews': typeof ResourcesReviewsRoute
  '/services/diy-downloads': typeof ServicesDiyDownloadsRoute
  '/services/post-production': typeof ServicesPostProductionRoute
  '/services/video-production': typeof ServicesVideoProductionRoute
  '/studio/approvals': typeof StudioApprovalsRoute
  '/studio/assistant': typeof StudioAssistantRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/ideas': typeof StudioIdeasRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/success': typeof StudioSuccessRoute
  '/blog': typeof BlogIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/campaigns': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-pov': typeof AiPovRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/contact': typeof ContactRoute
  '/content-strategy': typeof ContentStrategyRoute
  '/evergreen-pal': typeof EvergreenPalRoute
  '/faq': typeof FaqRoute
  '/find-your-pal': typeof FindYourPalRoute
  '/games': typeof GamesRoute
  '/integrations': typeof IntegrationsRoute
  '/membership': typeof MembershipRouteWithChildren
  '/pals': typeof PalsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/production-guide': typeof ProductionGuideRoute
  '/production-pricing': typeof ProductionPricingRoute
  '/reel-pal': typeof ReelPalRoute
  '/shop': typeof ShopRoute
  '/spotlight-pal': typeof SpotlightPalRoute
  '/startups': typeof StartupsRoute
  '/studio': typeof StudioRouteWithChildren
  '/system-pal': typeof SystemPalRoute
  '/terms': typeof TermsRoute
  '/video-system-assessment': typeof VideoSystemAssessmentRoute
  '/webinar': typeof WebinarRoute
  '/work': typeof WorkRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/membership/pricing': typeof MembershipPricingRoute
  '/membership/sprint': typeof MembershipSprintRoute
  '/resources/reviews': typeof ResourcesReviewsRoute
  '/services/diy-downloads': typeof ServicesDiyDownloadsRoute
  '/services/post-production': typeof ServicesPostProductionRoute
  '/services/video-production': typeof ServicesVideoProductionRoute
  '/studio/approvals': typeof StudioApprovalsRoute
  '/studio/assistant': typeof StudioAssistantRoute
  '/studio/billing': typeof StudioBillingRoute
  '/studio/brand': typeof StudioBrandRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/studio/ideas': typeof StudioIdeasRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/roadmap': typeof StudioRoadmapRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/studio/success': typeof StudioSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai-pov'
    | '/checkout'
    | '/checkout-success'
    | '/contact'
    | '/content-strategy'
    | '/evergreen-pal'
    | '/faq'
    | '/find-your-pal'
    | '/games'
    | '/integrations'
    | '/membership'
    | '/pals'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/production-guide'
    | '/production-pricing'
    | '/reel-pal'
    | '/shop'
    | '/spotlight-pal'
    | '/startups'
    | '/studio'
    | '/system-pal'
    | '/terms'
    | '/video-system-assessment'
    | '/webinar'
    | '/work'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/membership/pricing'
    | '/membership/sprint'
    | '/resources/reviews'
    | '/services/diy-downloads'
    | '/services/post-production'
    | '/services/video-production'
    | '/studio/approvals'
    | '/studio/assistant'
    | '/studio/billing'
    | '/studio/brand'
    | '/studio/calendar'
    | '/studio/dashboard'
    | '/studio/ideas'
    | '/studio/library'
    | '/studio/onboarding'
    | '/studio/roadmap'
    | '/studio/settings'
    | '/studio/success'
    | '/blog/'
    | '/studio/'
    | '/studio/campaigns/$campaignId'
    | '/studio/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai-pov'
    | '/checkout'
    | '/checkout-success'
    | '/contact'
    | '/content-strategy'
    | '/evergreen-pal'
    | '/faq'
    | '/find-your-pal'
    | '/games'
    | '/integrations'
    | '/membership'
    | '/pals'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/production-guide'
    | '/production-pricing'
    | '/reel-pal'
    | '/shop'
    | '/spotlight-pal'
    | '/startups'
    | '/system-pal'
    | '/terms'
    | '/video-system-assessment'
    | '/webinar'
    | '/work'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/membership/pricing'
    | '/membership/sprint'
    | '/resources/reviews'
    | '/services/diy-downloads'
    | '/services/post-production'
    | '/services/video-production'
    | '/studio/approvals'
    | '/studio/assistant'
    | '/studio/billing'
    | '/studio/brand'
    | '/studio/calendar'
    | '/studio/dashboard'
    | '/studio/ideas'
    | '/studio/library'
    | '/studio/onboarding'
    | '/studio/roadmap'
    | '/studio/settings'
    | '/studio/success'
    | '/blog'
    | '/studio'
    | '/studio/campaigns/$campaignId'
    | '/studio/campaigns'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai-pov'
    | '/checkout'
    | '/checkout-success'
    | '/contact'
    | '/content-strategy'
    | '/evergreen-pal'
    | '/faq'
    | '/find-your-pal'
    | '/games'
    | '/integrations'
    | '/membership'
    | '/pals'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/production-guide'
    | '/production-pricing'
    | '/reel-pal'
    | '/shop'
    | '/spotlight-pal'
    | '/startups'
    | '/studio'
    | '/system-pal'
    | '/terms'
    | '/video-system-assessment'
    | '/webinar'
    | '/work'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/membership/pricing'
    | '/membership/sprint'
    | '/resources/reviews'
    | '/services/diy-downloads'
    | '/services/post-production'
    | '/services/video-production'
    | '/studio/approvals'
    | '/studio/assistant'
    | '/studio/billing'
    | '/studio/brand'
    | '/studio/calendar'
    | '/studio/dashboard'
    | '/studio/ideas'
    | '/studio/library'
    | '/studio/onboarding'
    | '/studio/roadmap'
    | '/studio/settings'
    | '/studio/success'
    | '/blog/'
    | '/studio/'
    | '/studio/campaigns/$campaignId'
    | '/studio/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiPovRoute: typeof AiPovRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ContactRoute: typeof ContactRoute
  ContentStrategyRoute: typeof ContentStrategyRoute
  EvergreenPalRoute: typeof EvergreenPalRoute
  FaqRoute: typeof FaqRoute
  FindYourPalRoute: typeof FindYourPalRoute
  GamesRoute: typeof GamesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MembershipRoute: typeof MembershipRouteWithChildren
  PalsRoute: typeof PalsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ProductionGuideRoute: typeof ProductionGuideRoute
  ProductionPricingRoute: typeof ProductionPricingRoute
  ReelPalRoute: typeof ReelPalRoute
  ShopRoute: typeof ShopRoute
  SpotlightPalRoute: typeof SpotlightPalRoute
  StartupsRoute: typeof StartupsRoute
  StudioRoute: typeof StudioRouteWithChildren
  SystemPalRoute: typeof SystemPalRoute
  TermsRoute: typeof TermsRoute
  VideoSystemAssessmentRoute: typeof VideoSystemAssessmentRoute
  WebinarRoute: typeof WebinarRoute
  WorkRoute: typeof WorkRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  ResourcesReviewsRoute: typeof ResourcesReviewsRoute
  ServicesDiyDownloadsRoute: typeof ServicesDiyDownloadsRoute
  ServicesPostProductionRoute: typeof ServicesPostProductionRoute
  ServicesVideoProductionRoute: typeof ServicesVideoProductionRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinar': {
      id: '/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof WebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-system-assessment': {
      id: '/video-system-assessment'
      path: '/video-system-assessment'
      fullPath: '/video-system-assessment'
      preLoaderRoute: typeof VideoSystemAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-pal': {
      id: '/system-pal'
      path: '/system-pal'
      fullPath: '/system-pal'
      preLoaderRoute: typeof SystemPalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight-pal': {
      id: '/spotlight-pal'
      path: '/spotlight-pal'
      fullPath: '/spotlight-pal'
      preLoaderRoute: typeof SpotlightPalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel-pal': {
      id: '/reel-pal'
      path: '/reel-pal'
      fullPath: '/reel-pal'
      preLoaderRoute: typeof ReelPalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-pricing': {
      id: '/production-pricing'
      path: '/production-pricing'
      fullPath: '/production-pricing'
      preLoaderRoute: typeof ProductionPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-guide': {
      id: '/production-guide'
      path: '/production-guide'
      fullPath: '/production-guide'
      preLoaderRoute: typeof ProductionGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pals': {
      id: '/pals'
      path: '/pals'
      fullPath: '/pals'
      preLoaderRoute: typeof PalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-your-pal': {
      id: '/find-your-pal'
      path: '/find-your-pal'
      fullPath: '/find-your-pal'
      preLoaderRoute: typeof FindYourPalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evergreen-pal': {
      id: '/evergreen-pal'
      path: '/evergreen-pal'
      fullPath: '/evergreen-pal'
      preLoaderRoute: typeof EvergreenPalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-strategy': {
      id: '/content-strategy'
      path: '/content-strategy'
      fullPath: '/content-strategy'
      preLoaderRoute: typeof ContentStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pov': {
      id: '/ai-pov'
      path: '/ai-pov'
      fullPath: '/ai-pov'
      preLoaderRoute: typeof AiPovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/success': {
      id: '/studio/success'
      path: '/success'
      fullPath: '/studio/success'
      preLoaderRoute: typeof StudioSuccessRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/roadmap': {
      id: '/studio/roadmap'
      path: '/roadmap'
      fullPath: '/studio/roadmap'
      preLoaderRoute: typeof StudioRoadmapRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/onboarding': {
      id: '/studio/onboarding'
      path: '/onboarding'
      fullPath: '/studio/onboarding'
      preLoaderRoute: typeof StudioOnboardingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/library': {
      id: '/studio/library'
      path: '/library'
      fullPath: '/studio/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/ideas': {
      id: '/studio/ideas'
      path: '/ideas'
      fullPath: '/studio/ideas'
      preLoaderRoute: typeof StudioIdeasRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/dashboard': {
      id: '/studio/dashboard'
      path: '/dashboard'
      fullPath: '/studio/dashboard'
      preLoaderRoute: typeof StudioDashboardRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/calendar': {
      id: '/studio/calendar'
      path: '/calendar'
      fullPath: '/studio/calendar'
      preLoaderRoute: typeof StudioCalendarRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/brand': {
      id: '/studio/brand'
      path: '/brand'
      fullPath: '/studio/brand'
      preLoaderRoute: typeof StudioBrandRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/billing': {
      id: '/studio/billing'
      path: '/billing'
      fullPath: '/studio/billing'
      preLoaderRoute: typeof StudioBillingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/assistant': {
      id: '/studio/assistant'
      path: '/assistant'
      fullPath: '/studio/assistant'
      preLoaderRoute: typeof StudioAssistantRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/approvals': {
      id: '/studio/approvals'
      path: '/approvals'
      fullPath: '/studio/approvals'
      preLoaderRoute: typeof StudioApprovalsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/services/video-production': {
      id: '/services/video-production'
      path: '/services/video-production'
      fullPath: '/services/video-production'
      preLoaderRoute: typeof ServicesVideoProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/post-production': {
      id: '/services/post-production'
      path: '/services/post-production'
      fullPath: '/services/post-production'
      preLoaderRoute: typeof ServicesPostProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/diy-downloads': {
      id: '/services/diy-downloads'
      path: '/services/diy-downloads'
      fullPath: '/services/diy-downloads'
      preLoaderRoute: typeof ServicesDiyDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/reviews': {
      id: '/resources/reviews'
      path: '/resources/reviews'
      fullPath: '/resources/reviews'
      preLoaderRoute: typeof ResourcesReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/sprint': {
      id: '/membership/sprint'
      path: '/sprint'
      fullPath: '/membership/sprint'
      preLoaderRoute: typeof MembershipSprintRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/membership/pricing': {
      id: '/membership/pricing'
      path: '/pricing'
      fullPath: '/membership/pricing'
      preLoaderRoute: typeof MembershipPricingRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/campaigns/': {
      id: '/studio/campaigns/'
      path: '/campaigns'
      fullPath: '/studio/campaigns/'
      preLoaderRoute: typeof StudioCampaignsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/campaigns/$campaignId': {
      id: '/studio/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/studio/campaigns/$campaignId'
      preLoaderRoute: typeof StudioCampaignsCampaignIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface MembershipRouteChildren {
  MembershipPricingRoute: typeof MembershipPricingRoute
  MembershipSprintRoute: typeof MembershipSprintRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipPricingRoute: MembershipPricingRoute,
  MembershipSprintRoute: MembershipSprintRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface StudioRouteChildren {
  StudioApprovalsRoute: typeof StudioApprovalsRoute
  StudioAssistantRoute: typeof StudioAssistantRoute
  StudioBillingRoute: typeof StudioBillingRoute
  StudioBrandRoute: typeof StudioBrandRoute
  StudioCalendarRoute: typeof StudioCalendarRoute
  StudioDashboardRoute: typeof StudioDashboardRoute
  StudioIdeasRoute: typeof StudioIdeasRoute
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioOnboardingRoute: typeof StudioOnboardingRoute
  StudioRoadmapRoute: typeof StudioRoadmapRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioSuccessRoute: typeof StudioSuccessRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioCampaignsCampaignIdRoute: typeof StudioCampaignsCampaignIdRoute
  StudioCampaignsIndexRoute: typeof StudioCampaignsIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioApprovalsRoute: StudioApprovalsRoute,
  StudioAssistantRoute: StudioAssistantRoute,
  StudioBillingRoute: StudioBillingRoute,
  StudioBrandRoute: StudioBrandRoute,
  StudioCalendarRoute: StudioCalendarRoute,
  StudioDashboardRoute: StudioDashboardRoute,
  StudioIdeasRoute: StudioIdeasRoute,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioOnboardingRoute: StudioOnboardingRoute,
  StudioRoadmapRoute: StudioRoadmapRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioSuccessRoute: StudioSuccessRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioCampaignsCampaignIdRoute: StudioCampaignsCampaignIdRoute,
  StudioCampaignsIndexRoute: StudioCampaignsIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiPovRoute: AiPovRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ContactRoute: ContactRoute,
  ContentStrategyRoute: ContentStrategyRoute,
  EvergreenPalRoute: EvergreenPalRoute,
  FaqRoute: FaqRoute,
  FindYourPalRoute: FindYourPalRoute,
  GamesRoute: GamesRoute,
  IntegrationsRoute: IntegrationsRoute,
  MembershipRoute: MembershipRouteWithChildren,
  PalsRoute: PalsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ProductionGuideRoute: ProductionGuideRoute,
  ProductionPricingRoute: ProductionPricingRoute,
  ReelPalRoute: ReelPalRoute,
  ShopRoute: ShopRoute,
  SpotlightPalRoute: SpotlightPalRoute,
  StartupsRoute: StartupsRoute,
  StudioRoute: StudioRouteWithChildren,
  SystemPalRoute: SystemPalRoute,
  TermsRoute: TermsRoute,
  VideoSystemAssessmentRoute: VideoSystemAssessmentRoute,
  WebinarRoute: WebinarRoute,
  WorkRoute: WorkRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  ResourcesReviewsRoute: ResourcesReviewsRoute,
  ServicesDiyDownloadsRoute: ServicesDiyDownloadsRoute,
  ServicesPostProductionRoute: ServicesPostProductionRoute,
  ServicesVideoProductionRoute: ServicesVideoProductionRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
